-- ============================================================
-- VAL Jewelry Inventory Management System
-- Initial Schema Migration
-- ============================================================

-- Account Groups
CREATE TABLE IF NOT EXISTS grpmst (
    g_code   VARCHAR(3) PRIMARY KEY,
    g_desc   VARCHAR(30) NOT NULL
);

-- Account Master (parties, karigars, customers)
CREATE TABLE IF NOT EXISTS famst (
    ac_code  VARCHAR(5) PRIMARY KEY,
    sub_code VARCHAR(5),
    "desc"     VARCHAR(30) NOT NULL,
    a_name   VARCHAR(5),
    amt      NUMERIC(18,3) DEFAULT 0,
    rmk      VARCHAR(3),
    rate     NUMERIC(10,3) DEFAULT 0,
    per      NUMERIC(10,3) DEFAULT 0,
    opb      NUMERIC(18,3) DEFAULT 0,
    "date"     DATE,
    cat      CHAR(1),
    dia      CHAR(1),
    g_code   VARCHAR(3) REFERENCES grpmst(g_code)
);

-- Address book for parties
CREATE TABLE IF NOT EXISTS add_master (
    ac_code  VARCHAR(5) PRIMARY KEY REFERENCES famst(ac_code),
    add1     VARCHAR(30),
    add2     VARCHAR(30),
    add3     VARCHAR(30),
    pin      VARCHAR(7),
    tel_r1   VARCHAR(12),
    tel_o1   VARCHAR(12),
    mobile   VARCHAR(12),
    lst      VARCHAR(30),
    cst      VARCHAR(30),
    panno    VARCHAR(25),
    tinno    VARCHAR(25)
);

-- Item Types / Categories
CREATE TABLE IF NOT EXISTS type_master (
    "type"     VARCHAR(3) PRIMARY KEY,
    "desc"     VARCHAR(20) NOT NULL,
    desc1    VARCHAR(6),
    factor   SMALLINT DEFAULT 0,
    s_code   VARCHAR(5),
    s_code1  VARCHAR(5),
    p_code   VARCHAR(5),
    wtb      NUMERIC(8,3) DEFAULT 0,
    wt1a     NUMERIC(8,3) DEFAULT 0,
    wt1b     NUMERIC(8,3) DEFAULT 0,
    wt2a     NUMERIC(8,3) DEFAULT 0,
    wt2b     NUMERIC(8,3) DEFAULT 0,
    wt3a     NUMERIC(8,3) DEFAULT 0,
    wt3b     NUMERIC(8,3) DEFAULT 0,
    wt4a     NUMERIC(8,3) DEFAULT 0,
    wt4b     NUMERIC(8,3) DEFAULT 0,
    wt5a     NUMERIC(8,3) DEFAULT 0,
    wt5b     NUMERIC(8,3) DEFAULT 0,
    wt6a     NUMERIC(8,3) DEFAULT 0,
    wt6b     NUMERIC(8,3) DEFAULT 0,
    wt7a     NUMERIC(8,3) DEFAULT 0,
    wt7b     NUMERIC(8,3) DEFAULT 0,
    wt8a     NUMERIC(8,3) DEFAULT 0,
    wt8b     NUMERIC(8,3) DEFAULT 0,
    wta      NUMERIC(8,3) DEFAULT 0,
    sdesc    VARCHAR(30),
    sdesc1   VARCHAR(30)
);

-- Gold Rates
CREATE TABLE IF NOT EXISTS rate (
    id       SERIAL PRIMARY KEY,
    "date"     DATE NOT NULL UNIQUE,
    rate     NUMERIC(8,3) DEFAULT 0,
    rate1    NUMERIC(8,3) DEFAULT 0,
    s_rate   NUMERIC(8,3) DEFAULT 0,
    gtag     CHAR(1),
    qtag     CHAR(1),
    xtag     CHAR(1),
    sprn     CHAR(1)
);

-- Karigar Groups
CREATE TABLE IF NOT EXISTS kargr (
    ac_code  VARCHAR(5) PRIMARY KEY REFERENCES famst(ac_code),
    melt     NUMERIC(5,2) DEFAULT 0,
    chrg     NUMERIC(5,2) DEFAULT 0,
    mk_chrg  NUMERIC(10,3) DEFAULT 0,
    tag      CHAR(1)
);

-- Stock Positions
CREATE TABLE IF NOT EXISTS pstn (
    s_code   VARCHAR(5) PRIMARY KEY,
    "desc"     VARCHAR(30) NOT NULL,
    net_wt   NUMERIC(12,3) DEFAULT 0,
    rmk      VARCHAR(2)
);

-- Item Master
CREATE TABLE IF NOT EXISTS item (
    itcd         VARCHAR(7) PRIMARY KEY,
    set_code     VARCHAR(5),
    "desc"         VARCHAR(38) NOT NULL,
    fac          NUMERIC(10,3) DEFAULT 0,
    stamp        VARCHAR(20),
    purity       VARCHAR(2),
    melt         NUMERIC(12,3) DEFAULT 0,
    gross_wt     NUMERIC(10,3) DEFAULT 0,
    net_wt       NUMERIC(10,3) DEFAULT 0,
    ghat_wt      NUMERIC(10,3) DEFAULT 0,
    kundan_wt    NUMERIC(10,3) DEFAULT 0,
    extra_wt     NUMERIC(10,3) DEFAULT 0,
    gold_wt      NUMERIC(10,3) DEFAULT 0,
    kundn_wt     NUMERIC(10,3) DEFAULT 0,
    nakash_wt    NUMERIC(10,3) DEFAULT 0,
    stone_wt     NUMERIC(10,3) DEFAULT 0,
    prl_wt       NUMERIC(10,3) DEFAULT 0,
    rby_ct       NUMERIC(10,3) DEFAULT 0,
    rby_gm       NUMERIC(10,3) DEFAULT 0,
    eme_ct       NUMERIC(10,3) DEFAULT 0,
    eme_gm       NUMERIC(10,3) DEFAULT 0,
    plk_ct       NUMERIC(10,3) DEFAULT 0,
    plk_gm       NUMERIC(10,3) DEFAULT 0,
    stn1_name    VARCHAR(10),
    stn1_ct      NUMERIC(10,3) DEFAULT 0,
    stn1_gm      NUMERIC(10,3) DEFAULT 0,
    stn2_name    VARCHAR(10),
    stn2_ct      NUMERIC(10,3) DEFAULT 0,
    stn2_gm      NUMERIC(10,3) DEFAULT 0,
    stn3_name    VARCHAR(10),
    stn3_ct      NUMERIC(10,3) DEFAULT 0,
    stn3_gm      NUMERIC(10,3) DEFAULT 0,
    prls_gm      NUMERIC(10,3) DEFAULT 0,
    prlb_gm      NUMERIC(10,3) DEFAULT 0,
    rbyb_gm      NUMERIC(10,3) DEFAULT 0,
    emeb_gm      NUMERIC(10,3) DEFAULT 0,
    emebb_gm     NUMERIC(10,3) DEFAULT 0,
    prl1_name    VARCHAR(10),
    prl1_gm      NUMERIC(10,3) DEFAULT 0,
    srby_gm      NUMERIC(10,3) DEFAULT 0,
    seme_gm      NUMERIC(10,3) DEFAULT 0,
    scz_gm       NUMERIC(10,3) DEFAULT 0,
    snav_gm      NUMERIC(10,3) DEFAULT 0,
    prl2_name    VARCHAR(10),
    prl2_gm      NUMERIC(10,3) DEFAULT 0,
    prl3_name    VARCHAR(10),
    prl3_gm      NUMERIC(10,3) DEFAULT 0,
    narr1        VARCHAR(28),
    narr2        VARCHAR(28),
    mk_chrg      NUMERIC(10,3) DEFAULT 0,
    w_per        NUMERIC(10,3) DEFAULT 0,
    recpt_date   DATE,
    lot_no       VARCHAR(7),
    issue_no     VARCHAR(10),
    issue_date   DATE,
    ac_code      VARCHAR(5) REFERENCES famst(ac_code),
    stk_code     VARCHAR(5),
    cat          VARCHAR(5),
    kp           CHAR(1),
    tag          CHAR(1),
    cat1         CHAR(1),
    cna          VARCHAR(3),
    exb          CHAR(1),
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    updated_at   TIMESTAMPTZ DEFAULT NOW()
);

-- Item Tag/Barcode Block
CREATE TABLE IF NOT EXISTS itblk (
    itcd     VARCHAR(7) PRIMARY KEY REFERENCES item(itcd)
);

-- Item Code Change History
CREATE TABLE IF NOT EXISTS cdchange (
    id       SERIAL PRIMARY KEY,
    itcdf    VARCHAR(7) NOT NULL,
    itcdt    VARCHAR(7) NOT NULL,
    "date"     DATE NOT NULL
);

-- Lots (batches sent to karigar)
CREATE TABLE IF NOT EXISTS lot (
    t_no         VARCHAR(10) PRIMARY KEY,
    t_date       DATE NOT NULL,
    ac_code      VARCHAR(5) REFERENCES famst(ac_code),
    party        VARCHAR(30),
    lot_no       VARCHAR(6) UNIQUE NOT NULL,
    nos          INTEGER DEFAULT 0,
    gross_wt     NUMERIC(10,3) DEFAULT 0,
    kundan_wt    NUMERIC(10,3) DEFAULT 0,
    nakash_wt    NUMERIC(10,3) DEFAULT 0,
    stone_wt     NUMERIC(10,3) DEFAULT 0,
    pearl_wt     NUMERIC(10,3) DEFAULT 0,
    nos1         INTEGER DEFAULT 0,
    gross_wt1    NUMERIC(10,3) DEFAULT 0,
    adj_wt       NUMERIC(12,3) DEFAULT 0,
    kundan_wt1   NUMERIC(10,3) DEFAULT 0,
    nakash_wt1   NUMERIC(10,3) DEFAULT 0,
    stone_wt1    NUMERIC(10,3) DEFAULT 0,
    pearl_wt1    NUMERIC(10,3) DEFAULT 0,
    amt          NUMERIC(14,3) DEFAULT 0,
    g_rt         NUMERIC(12,3) DEFAULT 0,
    "desc"         VARCHAR(20)
);

-- Issue Vouchers (sending jewelry to karigar/party)
CREATE TABLE IF NOT EXISTS issue (
    t_no         VARCHAR(10) PRIMARY KEY,
    t_no1        VARCHAR(10),
    pre          VARCHAR(3),
    t_date       DATE NOT NULL,
    due_date     DATE,
    ac_code      VARCHAR(5) REFERENCES famst(ac_code),
    ac_code1     VARCHAR(5),
    tag          CHAR(1),
    nos          NUMERIC(10,3) DEFAULT 0,
    gross_wt     NUMERIC(10,3) DEFAULT 0,
    kundn_wt     NUMERIC(10,3) DEFAULT 0,
    nakash_wt    NUMERIC(10,3) DEFAULT 0,
    stone_wt     NUMERIC(10,3) DEFAULT 0,
    net_wt       NUMERIC(10,3) DEFAULT 0,
    net_per      NUMERIC(10,3) DEFAULT 0,
    kdn_per      NUMERIC(10,3) DEFAULT 0,
    nks_per      NUMERIC(10,3) DEFAULT 0,
    net_pure     NUMERIC(10,3) DEFAULT 0,
    kdn_pure     NUMERIC(10,3) DEFAULT 0,
    nks_pure     NUMERIC(10,3) DEFAULT 0,
    stn_amt      NUMERIC(10,3) DEFAULT 0,
    stn_rate     NUMERIC(10,3) DEFAULT 0,
    stn_pure     NUMERIC(12,3) DEFAULT 0,
    prls_gm      NUMERIC(10,3) DEFAULT 0,
    prls_rt      NUMERIC(10,3) DEFAULT 0,
    prls_amt     NUMERIC(10,3) DEFAULT 0,
    prlb_gm      NUMERIC(10,3) DEFAULT 0,
    prlb_rt      NUMERIC(10,3) DEFAULT 0,
    prlb_amt     NUMERIC(10,3) DEFAULT 0,
    rbyb_gm      NUMERIC(10,3) DEFAULT 0,
    rbyb_rt      NUMERIC(10,3) DEFAULT 0,
    rbyb_amt     NUMERIC(10,3) DEFAULT 0,
    emeb_gm      NUMERIC(10,3) DEFAULT 0,
    emeb_rt      NUMERIC(10,3) DEFAULT 0,
    emeb_amt     NUMERIC(10,3) DEFAULT 0,
    emebb_gm     NUMERIC(10,3) DEFAULT 0,
    emebb_rt     NUMERIC(10,3) DEFAULT 0,
    emebb_amt    NUMERIC(10,3) DEFAULT 0,
    prl1_name    VARCHAR(20),
    prl1_gm      NUMERIC(10,3) DEFAULT 0,
    prl1_rt      NUMERIC(10,3) DEFAULT 0,
    prl1_amt     NUMERIC(10,3) DEFAULT 0,
    srby_gm      NUMERIC(10,3) DEFAULT 0,
    srby_rt      NUMERIC(10,3) DEFAULT 0,
    srby_amt     NUMERIC(10,3) DEFAULT 0,
    seme_gm      NUMERIC(10,3) DEFAULT 0,
    seme_rt      NUMERIC(10,3) DEFAULT 0,
    seme_amt     NUMERIC(10,3) DEFAULT 0,
    scz_gm       NUMERIC(10,3) DEFAULT 0,
    scz_rt       NUMERIC(10,3) DEFAULT 0,
    scz_amt      NUMERIC(10,3) DEFAULT 0,
    snav_gm      NUMERIC(10,3) DEFAULT 0,
    snav_rt      NUMERIC(10,3) DEFAULT 0,
    snav_amt     NUMERIC(10,3) DEFAULT 0,
    prl2_name    VARCHAR(20),
    prl2_gm      NUMERIC(10,3) DEFAULT 0,
    prl2_rt      NUMERIC(10,3) DEFAULT 0,
    prl2_amt     NUMERIC(10,3) DEFAULT 0,
    per_pure     NUMERIC(10,3) DEFAULT 0,
    prl3_name    VARCHAR(20),
    prl3_gm      NUMERIC(10,3) DEFAULT 0,
    prl3_rt      NUMERIC(10,3) DEFAULT 0,
    prl3_amt     NUMERIC(10,3) DEFAULT 0,
    pure_wt      NUMERIC(10,3) DEFAULT 0,
    discount     NUMERIC(10,3) DEFAULT 0,
    pure_final   NUMERIC(10,3) DEFAULT 0,
    kundan_wt    NUMERIC(10,3) DEFAULT 0,
    lot_wt       NUMERIC(12,3) DEFAULT 0,
    rate         NUMERIC(10,3) DEFAULT 0,
    narr         VARCHAR(70),
    narr1        VARCHAR(70),
    "desc"         VARCHAR(50),
    bill_amt     NUMERIC(12,3) DEFAULT 0,
    tc           VARCHAR(2),
    exb          CHAR(1),
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    updated_at   TIMESTAMPTZ DEFAULT NOW()
);

-- Issue Detail Lines
CREATE TABLE IF NOT EXISTS isdetl (
    id           SERIAL PRIMARY KEY,
    t_no         VARCHAR(10) REFERENCES issue(t_no) ON DELETE CASCADE,
    t_date       DATE,
    recpt_no     VARCHAR(10),
    recpt_date   DATE,
    itcd         VARCHAR(7) REFERENCES item(itcd),
    ac_code      VARCHAR(5) REFERENCES famst(ac_code),
    itdesc       VARCHAR(20),
    nos          NUMERIC(10,3) DEFAULT 0,
    gross_wt     NUMERIC(10,3) DEFAULT 0,
    kundn_wt     NUMERIC(10,3) DEFAULT 0,
    nakash_wt    NUMERIC(10,3) DEFAULT 0,
    stone_wt     NUMERIC(10,3) DEFAULT 0,
    net_wt       NUMERIC(10,3) DEFAULT 0,
    cna          VARCHAR(3),
    ghat_wt      NUMERIC(10,3) DEFAULT 0,
    kundan_wt    NUMERIC(10,3) DEFAULT 0,
    extra_wt     NUMERIC(10,3) DEFAULT 0,
    prls_gm      NUMERIC(10,3) DEFAULT 0,
    prlb_gm      NUMERIC(10,3) DEFAULT 0,
    rbyb_gm      NUMERIC(10,3) DEFAULT 0,
    emeb_gm      NUMERIC(10,3) DEFAULT 0,
    emebb_gm     NUMERIC(10,3) DEFAULT 0,
    prl1_name    VARCHAR(15),
    prl1_gm      NUMERIC(10,3) DEFAULT 0,
    srby_gm      NUMERIC(10,3) DEFAULT 0,
    seme_gm      NUMERIC(10,3) DEFAULT 0,
    scz_gm       NUMERIC(10,3) DEFAULT 0,
    snav_gm      NUMERIC(10,3) DEFAULT 0,
    prl2_name    VARCHAR(15),
    prl2_gm      NUMERIC(10,3) DEFAULT 0,
    prl3_name    VARCHAR(15),
    prl3_gm      NUMERIC(10,3) DEFAULT 0,
    cat          CHAR(1),
    narr         VARCHAR(20),
    narr1        VARCHAR(35),
    narr2        VARCHAR(35),
    exb          CHAR(1)
);

-- Receipt Vouchers (receiving jewelry back from karigar/party)
CREATE TABLE IF NOT EXISTS recpt (
    t_no         VARCHAR(10) PRIMARY KEY,
    t_no1        VARCHAR(10),
    pre          VARCHAR(3),
    t_date       DATE NOT NULL,
    due_date     DATE,
    ac_code      VARCHAR(5) REFERENCES famst(ac_code),
    ac_code1     VARCHAR(5),
    tag          CHAR(1),
    nos          NUMERIC(10,3) DEFAULT 0,
    gross_wt     NUMERIC(12,3) DEFAULT 0,
    kundn_wt     NUMERIC(12,3) DEFAULT 0,
    nakash_wt    NUMERIC(12,3) DEFAULT 0,
    stone_wt     NUMERIC(12,3) DEFAULT 0,
    net_wt       NUMERIC(12,3) DEFAULT 0,
    net_per      NUMERIC(10,3) DEFAULT 0,
    kdn_per      NUMERIC(10,3) DEFAULT 0,
    nks_per      NUMERIC(10,3) DEFAULT 0,
    net_pure     NUMERIC(10,3) DEFAULT 0,
    kdn_pure     NUMERIC(10,3) DEFAULT 0,
    nks_pure     NUMERIC(10,3) DEFAULT 0,
    stn_amt      NUMERIC(14,3) DEFAULT 0,
    stn_rate     NUMERIC(10,3) DEFAULT 0,
    stn_pure     NUMERIC(12,3) DEFAULT 0,
    prls_gm      NUMERIC(10,3) DEFAULT 0,
    prls_rt      NUMERIC(10,3) DEFAULT 0,
    prls_amt     NUMERIC(10,3) DEFAULT 0,
    prlb_gm      NUMERIC(10,3) DEFAULT 0,
    prlb_rt      NUMERIC(10,3) DEFAULT 0,
    prlb_amt     NUMERIC(10,3) DEFAULT 0,
    rbyb_gm      NUMERIC(10,3) DEFAULT 0,
    rbyb_rt      NUMERIC(10,3) DEFAULT 0,
    rbyb_amt     NUMERIC(10,3) DEFAULT 0,
    emeb_gm      NUMERIC(10,3) DEFAULT 0,
    emeb_rt      NUMERIC(10,3) DEFAULT 0,
    emeb_amt     NUMERIC(10,3) DEFAULT 0,
    emebb_gm     NUMERIC(10,3) DEFAULT 0,
    emebb_rt     NUMERIC(10,3) DEFAULT 0,
    emebb_amt    NUMERIC(10,3) DEFAULT 0,
    prl1_name    VARCHAR(20),
    prl1_gm      NUMERIC(10,3) DEFAULT 0,
    prl1_rt      NUMERIC(10,3) DEFAULT 0,
    prl1_amt     NUMERIC(10,3) DEFAULT 0,
    srby_gm      NUMERIC(10,3) DEFAULT 0,
    srby_rt      NUMERIC(10,3) DEFAULT 0,
    srby_amt     NUMERIC(10,3) DEFAULT 0,
    seme_gm      NUMERIC(10,3) DEFAULT 0,
    seme_rt      NUMERIC(10,3) DEFAULT 0,
    seme_amt     NUMERIC(10,3) DEFAULT 0,
    scz_gm       NUMERIC(10,3) DEFAULT 0,
    scz_rt       NUMERIC(10,3) DEFAULT 0,
    scz_amt      NUMERIC(10,3) DEFAULT 0,
    snav_gm      NUMERIC(10,3) DEFAULT 0,
    snav_rt      NUMERIC(10,3) DEFAULT 0,
    snav_amt     NUMERIC(10,3) DEFAULT 0,
    prl2_name    VARCHAR(20),
    prl2_gm      NUMERIC(10,3) DEFAULT 0,
    prl2_rt      NUMERIC(10,3) DEFAULT 0,
    prl2_amt     NUMERIC(10,3) DEFAULT 0,
    prl3_name    VARCHAR(20),
    prl3_gm      NUMERIC(10,3) DEFAULT 0,
    prl3_rt      NUMERIC(10,3) DEFAULT 0,
    prl3_amt     NUMERIC(10,3) DEFAULT 0,
    per_pure     NUMERIC(10,3) DEFAULT 0,
    pure_wt      NUMERIC(12,3) DEFAULT 0,
    discount     NUMERIC(10,3) DEFAULT 0,
    pure_final   NUMERIC(12,3) DEFAULT 0,
    kundan_wt    NUMERIC(10,3) DEFAULT 0,
    lot_wt       NUMERIC(12,3) DEFAULT 0,
    rate         NUMERIC(10,3) DEFAULT 0,
    narr         VARCHAR(70),
    narr1        VARCHAR(70),
    "desc"         VARCHAR(50),
    bill_amt     NUMERIC(12,3) DEFAULT 0,
    tc           VARCHAR(2),
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    updated_at   TIMESTAMPTZ DEFAULT NOW()
);

-- Receipt Detail Lines
CREATE TABLE IF NOT EXISTS rcdetl (
    id           SERIAL PRIMARY KEY,
    t_no         VARCHAR(10) REFERENCES recpt(t_no) ON DELETE CASCADE,
    t_date       DATE,
    ac_code      VARCHAR(5) REFERENCES famst(ac_code),
    itcd         VARCHAR(7) REFERENCES item(itcd),
    fac          SMALLINT DEFAULT 0,
    itdesc       VARCHAR(20),
    lot_no       VARCHAR(7),
    gross_wt     NUMERIC(10,3) DEFAULT 0,
    net_wt       NUMERIC(10,3) DEFAULT 0,
    ghat_wt      NUMERIC(10,3) DEFAULT 0,
    kundan_wt    NUMERIC(10,3) DEFAULT 0,
    extra_wt     NUMERIC(10,3) DEFAULT 0,
    gold_wt      NUMERIC(10,3) DEFAULT 0,
    kundn_wt     NUMERIC(10,3) DEFAULT 0,
    nakash_wt    NUMERIC(10,3) DEFAULT 0,
    stone_wt     NUMERIC(10,3) DEFAULT 0,
    prl_wt       NUMERIC(10,3) DEFAULT 0,
    rby_ct       NUMERIC(10,3) DEFAULT 0,
    rby_gm       NUMERIC(10,3) DEFAULT 0,
    eme_ct       NUMERIC(10,3) DEFAULT 0,
    eme_gm       NUMERIC(10,3) DEFAULT 0,
    plk_ct       NUMERIC(10,3) DEFAULT 0,
    plk_gm       NUMERIC(10,3) DEFAULT 0,
    stn1_name    VARCHAR(20),
    stn1_ct      NUMERIC(10,3) DEFAULT 0,
    stn1_gm      NUMERIC(10,3) DEFAULT 0,
    stn2_name    VARCHAR(20),
    stn2_ct      NUMERIC(10,3) DEFAULT 0,
    stn2_gm      NUMERIC(10,3) DEFAULT 0,
    stn3_name    VARCHAR(20),
    stn3_ct      NUMERIC(10,3) DEFAULT 0,
    stn3_gm      NUMERIC(10,3) DEFAULT 0,
    prls_gm      NUMERIC(10,3) DEFAULT 0,
    prlb_gm      NUMERIC(10,3) DEFAULT 0,
    rbyb_gm      NUMERIC(10,3) DEFAULT 0,
    emeb_gm      NUMERIC(10,3) DEFAULT 0,
    emebb_gm     NUMERIC(10,3) DEFAULT 0,
    prl1_name    VARCHAR(20),
    prl1_gm      NUMERIC(10,3) DEFAULT 0,
    srby_gm      NUMERIC(10,3) DEFAULT 0,
    seme_gm      NUMERIC(10,3) DEFAULT 0,
    scz_gm       NUMERIC(10,3) DEFAULT 0,
    snav_gm      NUMERIC(10,3) DEFAULT 0,
    prl2_name    VARCHAR(20),
    prl2_gm      NUMERIC(10,3) DEFAULT 0,
    prl3_name    VARCHAR(20),
    prl3_gm      NUMERIC(10,3) DEFAULT 0,
    cna          VARCHAR(3),
    bill_amt     NUMERIC(12,3) DEFAULT 0,
    cat          CHAR(1),
    narr1        VARCHAR(35),
    narr2        VARCHAR(35)
);

-- Sales Vouchers
CREATE TABLE IF NOT EXISTS sale (
    vouch_no     VARCHAR(10) PRIMARY KEY,
    ovno         VARCHAR(10),
    pre          VARCHAR(2),
    vouch_no1    VARCHAR(5),
    vouch_date   DATE NOT NULL,
    ac_code      VARCHAR(5) REFERENCES famst(ac_code),
    name         VARCHAR(31),
    add1         VARCHAR(30),
    add2         VARCHAR(30),
    phone_no     VARCHAR(12),
    phone_no1    VARCHAR(12),
    sman         VARCHAR(9),
    nos          INTEGER DEFAULT 0,
    gross_wt     NUMERIC(10,3) DEFAULT 0,
    kundn_wt     NUMERIC(10,3) DEFAULT 0,
    nakash_wt    NUMERIC(10,3) DEFAULT 0,
    stone_wt     NUMERIC(10,3) DEFAULT 0,
    net_wt       NUMERIC(10,3) DEFAULT 0,
    net_per      NUMERIC(10,3) DEFAULT 0,
    kdn_per      NUMERIC(10,3) DEFAULT 0,
    nks_per      NUMERIC(10,3) DEFAULT 0,
    net_pure     NUMERIC(10,3) DEFAULT 0,
    kdn_pure     NUMERIC(10,3) DEFAULT 0,
    nks_pure     NUMERIC(10,3) DEFAULT 0,
    stn_amt      NUMERIC(10,3) DEFAULT 0,
    stn_rate     NUMERIC(10,3) DEFAULT 0,
    stn_pure     NUMERIC(12,3) DEFAULT 0,
    prls_gm      NUMERIC(10,3) DEFAULT 0,
    prls_rt      NUMERIC(10,3) DEFAULT 0,
    prls_amt     NUMERIC(10,3) DEFAULT 0,
    prlb_gm      NUMERIC(10,3) DEFAULT 0,
    prlb_rt      NUMERIC(10,3) DEFAULT 0,
    prlb_amt     NUMERIC(10,3) DEFAULT 0,
    rbyb_gm      NUMERIC(10,3) DEFAULT 0,
    rbyb_rt      NUMERIC(10,3) DEFAULT 0,
    rbyb_amt     NUMERIC(10,3) DEFAULT 0,
    emeb_gm      NUMERIC(10,3) DEFAULT 0,
    emeb_rt      NUMERIC(10,3) DEFAULT 0,
    emeb_amt     NUMERIC(10,3) DEFAULT 0,
    emebb_gm     NUMERIC(10,3) DEFAULT 0,
    emebb_rt     NUMERIC(10,3) DEFAULT 0,
    emebb_amt    NUMERIC(10,3) DEFAULT 0,
    prl1_name    VARCHAR(20),
    prl1_gm      NUMERIC(10,3) DEFAULT 0,
    prl1_rt      NUMERIC(10,3) DEFAULT 0,
    prl1_amt     NUMERIC(10,3) DEFAULT 0,
    srby_gm      NUMERIC(10,3) DEFAULT 0,
    srby_rt      NUMERIC(10,3) DEFAULT 0,
    srby_amt     NUMERIC(10,3) DEFAULT 0,
    seme_gm      NUMERIC(10,3) DEFAULT 0,
    seme_rt      NUMERIC(10,3) DEFAULT 0,
    seme_amt     NUMERIC(10,3) DEFAULT 0,
    scz_gm       NUMERIC(10,3) DEFAULT 0,
    scz_rt       NUMERIC(10,3) DEFAULT 0,
    scz_amt      NUMERIC(10,3) DEFAULT 0,
    snav_gm      NUMERIC(10,3) DEFAULT 0,
    snav_rt      NUMERIC(10,3) DEFAULT 0,
    snav_amt     NUMERIC(10,3) DEFAULT 0,
    prl2_name    VARCHAR(20),
    prl2_gm      NUMERIC(10,3) DEFAULT 0,
    prl2_rt      NUMERIC(10,3) DEFAULT 0,
    prl2_amt     NUMERIC(10,3) DEFAULT 0,
    prl3_name    VARCHAR(20),
    prl3_gm      NUMERIC(10,3) DEFAULT 0,
    prl3_rt      NUMERIC(10,3) DEFAULT 0,
    prl3_amt     NUMERIC(10,3) DEFAULT 0,
    pure_wt      NUMERIC(10,3) DEFAULT 0,
    discount     NUMERIC(10,3) DEFAULT 0,
    pure_final   NUMERIC(10,3) DEFAULT 0,
    narr         VARCHAR(35),
    narr1        VARCHAR(35),
    btype        CHAR(1),
    created_at   TIMESTAMPTZ DEFAULT NOW(),
    updated_at   TIMESTAMPTZ DEFAULT NOW()
);

-- Purchase Vouchers
CREATE TABLE IF NOT EXISTS purch (
    vouch_no     VARCHAR(10) PRIMARY KEY,
    pre          VARCHAR(2),
    vouch_no1    VARCHAR(5),
    vouch_date   DATE NOT NULL,
    ac_code      VARCHAR(5) REFERENCES famst(ac_code),
    name         VARCHAR(30),
    add1         VARCHAR(30),
    add2         VARCHAR(30),
    rate         NUMERIC(10,3) DEFAULT 0,
    gross_wt     NUMERIC(10,3) DEFAULT 0,
    net_wt       NUMERIC(10,3) DEFAULT 0,
    bill_amt     NUMERIC(10,3) DEFAULT 0,
    narr         VARCHAR(30),
    narr2        VARCHAR(30),
    narr3        VARCHAR(30),
    narr4        VARCHAR(30),
    narr5        VARCHAR(30),
    narr6        VARCHAR(30),
    narr7        VARCHAR(30),
    bill_no1     VARCHAR(7),
    bill_no2     VARCHAR(7),
    bill_no3     VARCHAR(7),
    bill_no4     VARCHAR(7),
    rmk          VARCHAR(50),
    tag          CHAR(1),
    post         CHAR(1),
    created_at   TIMESTAMPTZ DEFAULT NOW()
);

-- Ledger / Financial Transactions
CREATE TABLE IF NOT EXISTS tran (
    t_no         VARCHAR(10) PRIMARY KEY,
    vouch_no1    VARCHAR(10),
    t_date       DATE NOT NULL,
    ac_code      VARCHAR(5) REFERENCES famst(ac_code),
    narr         VARCHAR(50),
    narr1        VARCHAR(50),
    narr2        VARCHAR(50),
    amt          NUMERIC(18,3) DEFAULT 0,
    net_wt       NUMERIC(12,3) DEFAULT 0,
    bill_no      VARCHAR(10),
    tc           VARCHAR(5),
    post         CHAR(1),
    amt1         NUMERIC(18,3) DEFAULT 0,
    rate1        NUMERIC(18,3) DEFAULT 0,
    net_wt1      NUMERIC(12,3) DEFAULT 0,
    rcut_dt1     DATE,
    amt2         NUMERIC(18,3) DEFAULT 0,
    rate2        NUMERIC(12,3) DEFAULT 0,
    net_wt2      NUMERIC(12,3) DEFAULT 0,
    rcut_dt2     DATE,
    amt3         NUMERIC(18,3) DEFAULT 0,
    rate3        NUMERIC(12,3) DEFAULT 0,
    net_wt3      NUMERIC(12,3) DEFAULT 0,
    rcut_dt3     DATE,
    created_at   TIMESTAMPTZ DEFAULT NOW()
);

-- Money Receipts
CREATE TABLE IF NOT EXISTS mr (
    vouch_no     VARCHAR(5) PRIMARY KEY,
    vouch_date   DATE NOT NULL,
    name         VARCHAR(30),
    add1         VARCHAR(30),
    add2         VARCHAR(30),
    chq_no       VARCHAR(15),
    chq_dt       DATE,
    drawn_on     VARCHAR(30),
    amount       NUMERIC(10,3) DEFAULT 0,
    narr         VARCHAR(50),
    tag          CHAR(1),
    agst         CHAR(1),
    created_at   TIMESTAMPTZ DEFAULT NOW()
);

-- Account Balances / Outstanding
CREATE TABLE IF NOT EXISTS out_balances (
    ac_code      VARCHAR(5) PRIMARY KEY REFERENCES famst(ac_code),
    rmk          VARCHAR(3),
    "desc"         VARCHAR(30),
    amt          NUMERIC(18,3) DEFAULT 0,
    wt           NUMERIC(18,3) DEFAULT 0,
    amtdr        NUMERIC(18,3) DEFAULT 0,
    amtcr        NUMERIC(18,3) DEFAULT 0,
    wtdr         NUMERIC(18,3) DEFAULT 0,
    wtcr         NUMERIC(18,3) DEFAULT 0
);

-- Scheme (installment tracking)
CREATE TABLE IF NOT EXISTS schm (
    vouch_no     VARCHAR(5) PRIMARY KEY,
    vouch_date   DATE NOT NULL,
    m_no         VARCHAR(5),
    name         VARCHAR(30),
    add1         VARCHAR(30),
    add2         VARCHAR(30),
    group_code   CHAR(1),
    chq_no       VARCHAR(15),
    chq_dt       DATE,
    drawn_on     VARCHAR(30),
    nos          INTEGER DEFAULT 0,
    ins_no       INTEGER DEFAULT 0,
    amount       NUMERIC(10,3) DEFAULT 0,
    tag          CHAR(1),
    schm         VARCHAR(3),
    g_rate       NUMERIC(12,3) DEFAULT 0,
    narr         VARCHAR(50),
    narr1        VARCHAR(50),
    created_at   TIMESTAMPTZ DEFAULT NOW()
);

-- Users (for multi-user access)
CREATE TABLE IF NOT EXISTS users (
    id           SERIAL PRIMARY KEY,
    username     VARCHAR(50) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    full_name    VARCHAR(100),
    role         VARCHAR(20) DEFAULT 'user',
    active       BOOLEAN DEFAULT TRUE,
    created_at   TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_item_ac_code ON item(ac_code);
CREATE INDEX IF NOT EXISTS idx_item_lot_no ON item(lot_no);
CREATE INDEX IF NOT EXISTS idx_item_cat ON item(cat);
CREATE INDEX IF NOT EXISTS idx_isdetl_t_no ON isdetl(t_no);
CREATE INDEX IF NOT EXISTS idx_isdetl_itcd ON isdetl(itcd);
CREATE INDEX IF NOT EXISTS idx_isdetl_ac_code ON isdetl(ac_code);
CREATE INDEX IF NOT EXISTS idx_rcdetl_t_no ON rcdetl(t_no);
CREATE INDEX IF NOT EXISTS idx_rcdetl_itcd ON rcdetl(itcd);
CREATE INDEX IF NOT EXISTS idx_issue_t_date ON issue(t_date);
CREATE INDEX IF NOT EXISTS idx_issue_ac_code ON issue(ac_code);
CREATE INDEX IF NOT EXISTS idx_recpt_t_date ON recpt(t_date);
CREATE INDEX IF NOT EXISTS idx_recpt_ac_code ON recpt(ac_code);
CREATE INDEX IF NOT EXISTS idx_sale_vouch_date ON sale(vouch_date);
CREATE INDEX IF NOT EXISTS idx_sale_ac_code ON sale(ac_code);
CREATE INDEX IF NOT EXISTS idx_tran_t_date ON tran(t_date);
CREATE INDEX IF NOT EXISTS idx_tran_ac_code ON tran(ac_code);
CREATE INDEX IF NOT EXISTS idx_famst_g_code ON famst(g_code);
